[package]
name = "digital_signatures_ed25519"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
rand = "0.8" 
rand_core = "0.9.3"
hex = "0.4.3"
sha2 = "0.10"
